services:
  frontend:
    image: bymave/frontend-morales-systeam:latest
    ports:
      - "8080:80"
    networks:
      - sysmorales-network

  backend:
    image: bymave/backend-morales-systeam:latest
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}  # Inyectamos las credenciales de Google
    networks:
      - sysmorales-network

networks:
  sysmorales-network:
    driver: bridge
