services:
  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    image: bymave/frontend-morales-systeam:latest
    ports:
      - "80:80"  # El frontend se servirá en el puerto 80 a través de Nginx dentro del contenedor
    networks:
      - sysmorales-network

  backend:
    build: 
      context: ./BackendApiRest
      dockerfile: Dockerfile
    image: bymave/backend-morales-systeam:latest
    environment:
      MYSQL_HOST: 192.168.x.x  # Cambia a la IP de tu VPS o 'localhost' si es el mismo servidor
      MYSQL_DATABASE: nombre_base_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    networks:
      - sysmorales-network

networks:
  sysmorales-network:
    driver: bridge
